version: '3.9'

services:
  xtasks_db:
    image: postgres
    container_name: xtasks_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=alfredo
      - POSTGRES_PASSWORD=alfredo03
      - POSTGRES_DB=xtasks_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes:
  pgdata:
    driver: local